%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/zli/Desktop/postTrack/Data/antInfectionStatus.csv
%
% Auto-generated by MATLAB on 21-Apr-2022 17:41:09

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["ColonyID", "Colour", "InfectionStatus"];
opts.VariableTypes = ["categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["ColonyID", "Colour", "InfectionStatus"], "EmptyFieldRule", "auto");

% Import the data
antInfectionStatus = readtable("antInfectionStatus.csv", opts);


%% Clear temporary variables
clear opts